version: "3"
services:
  myapp:
    image: myapp
    restart: always
    build: .
    ports:
      - 8003:6003
    environment:
     MYSQL_HOST: mysqldb
     MYSQL_USER: root
     MYSQL_PASSWORD: root
     MYSQL_PORT: 3306
  
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      